### ISSUE TITLE
[BUG] null property error without character set

### ISSUE THREAD

**Issue by Ikabodo** [p4535992/foundryvtt-chat-portrait#1]
**Module Version:** v0.8.3

**Describe the bug**
I'm getting spammed (as a GM) by these warnings when this module is used in conjuction with dfreds convenient effects, but it happens whit any whisper when the GM does not have a character set.

**To Reproduce**
1. Make sure there is no character selected for the GM
2. Click Convenient Effects (or just do a whisper to GM)
3. See error

**Screenshots**
![image](https://user-images.githubusercontent.com/7766890/190931847-6bc8a61e-6b8d-43a8-ae96-8855fcc70c9a.png)

**Foundry Version:** v10.285
**Game System:** v2.0.2

**Comment by p4535992** [comment]
Add some check, now the exception should be managed, sorry for the delay
