### ISSUE TITLE
V9 download

### ISSUE THREAD

**Issue by Liviu50** [p4535992/foundryvtt-chat-portrait#12]
Good day, i wanted to include this module into my campaigns.
For reasons of update and stuff, i have to use foundry V9 instead of the latest, sadly if i try to download your module (even if it shows in the list) it says i need to upgrade to v10 because the module is not configured for V9.
is there anyway i could get a v9 module or get the latest that was good for v9 foundry?
thanks a bunch!

**Comment by p4535992** [comment]
You can use the old repository for 9 
https://github.com/ShoyuVanilla/FoundryVTT-Chat-Portrait/releases/download/v0.7.4/module.json
, but is strange if you are on 9 you should see only that repository on 9.
