### ISSUE TITLE
[BUG] Compatibility with module https://github.com/YourFavouriteOreo/VTT-Chat-GIFs/

### ISSUE THREAD

**Issue by Profoundant89** [p4535992/foundryvtt-chat-portrait#20]
![image](https://user-images.githubusercontent.com/123834984/215286817-a0388a07-749e-4745-8642-805c20046c86.png)

image sits on top of the chat log, cant get it to go away, while not wanting to use it.

**Comment by p4535992** [comment]
I's seem a [Chat](https://github.com/YourFavouriteOreo/VTT-Chat-GIFs) issue. Even with Chat Portrait disabled i got the css style behaviour.
