### ISSUE TITLE
Chat cards look different for some actors

### ISSUE THREAD

**Issue by skarr71** [p4535992/foundryvtt-chat-portrait#22]
It's not game breaking for sure, but it is annoying.  It doesn't log anything abnormal in the debugging window.  Actions for some actors are not formatting right.  I disabled all mods except Chat Portraits 0.8.36, this is using the PF2e ruleset v4.7.4 and Foundry v10 build 291. 

![Foundryvtt chat log](https://user-images.githubusercontent.com/6988879/220175940-84c02f88-c788-444d-a48b-d5226ff31fd3.png)

**Comment by Wonton77** [comment]
Probably the same issue, Chat Portrait 0.8.36, Pathfinder 2e 4.8.3

Some chat cards look like they're getting "squished" - the text runs out of space and overflows onto another line.

![image](https://user-images.githubusercontent.com/121756549/222620608-f4e38010-6924-4800-9162-ded9ab805001.png)
![image](https://user-images.githubusercontent.com/121756549/222620989-0d702339-6b6f-4a82-a32b-c66a16e7b119.png)

**Comment by p4535992** [comment]
Try out 0.8.38 and tell me if the issue is resolved

**Comment by Wonton77** [comment]
> Try out 0.8.38 and tell me if the issue is resolved

Seems to be fixed, thanks!
