### ISSUE TITLE
[BUG] Error on load re: en.json, potentially other localizations

### ISSUE THREAD

**Issue by esheyw** [p4535992/foundryvtt-chat-portrait#28]
CP v0.8.41, pf2e 4.8.3, foundry 10.291

![](https://i.imgur.com/OYqRTEx.png)

**Comment by Angor-de-Redjak** [comment]
I have the same thing in D&D5 2.1.5, same versions as Esheyw tor the rest.

`TypeError: Unable to parse localization file modules/chat-portrait/languages/fr.json. can't assign to property "warning" on "Cliquez pour parler hors du personnage pour le prochain message. Double-cliquez pour continuer ainsi jusqu'\xE0 ce que vous cliquiez \xE0 nouveau.": not an object
[Detected 1 package: lib-wrapper]
    setProperty commons.js:2194
    expandObject commons.js:1961
    _loadTranslationFile foundry.js:6772
    _getTranslations foundry.js:6705
    _getTranslations foundry.js:6704
    setLanguage foundry.js:6635
    initialize foundry.js:6601
    initialize foundry.js:7816
    call_wrapped libWrapper-wrapper.js:507
    libWrapperInit libWrapper-api.js:803
    initialize#0 libWrapper-wrapper.js:187
    <anonymous> foundry.js:79693
    async* foundry.js:79675
foundry.js:747:30
    onError foundry.js:747
    call_wrapped libWrapper-wrapper.js:507
    <anonyme> listeners.js:135
    onError#0 libWrapper-wrapper.js:187
    _loadTranslationFile foundry.js:6774
    _getTranslations foundry.js:6705
    _getTranslations foundry.js:6704
    setLanguage foundry.js:6635
    initialize foundry.js:6601
    initialize foundry.js:7816
    call_wrapped libWrapper-wrapper.js:507
    libWrapperInit libWrapper-api.js:803
    initialize#0 libWrapper-wrapper.js:187
    <anonyme> foundry.js:79693
    <anonyme> foundry.js:79675
`

**Comment by InstantZzz** [comment]
I too have this issue in Call of Cthulhu 7E v0.9.2

**Comment by thejoester** [comment]
also getting this error and my settings are all messed up: 
![image](https://user-images.githubusercontent.com/7744795/225292324-fd9f9237-8a1f-4f99-8a0a-aa2122af984f.png)

**Comment by p4535992** [comment]
Should be fixed.

**Comment by esheyw** [comment]
Yep, no error on load, settings localizing properly. Thanks!

**Comment by Angor-de-Redjak** [comment]
I still get an error on CP 0.8.43

```
TypeError: Unable to parse localization file modules/chat-portrait/languages/fr.json. can't assign to property "warning" on "Cliquez pour parler hors du personnage pour le prochain message. Double-cliquez pour continuer ainsi jusqu'\xE0 ce que vous cliquiez \xE0 nouveau.": not an object
[Detected 1 package: lib-wrapper]
    setProperty commons.js:2194
    expandObject commons.js:1961
    _loadTranslationFile foundry.js:6772
    _getTranslations foundry.js:6705
    _getTranslations foundry.js:6704
    setLanguage foundry.js:6635
    initialize foundry.js:6601
    initialize foundry.js:7816
    call_wrapped libWrapper-wrapper.js:507
    libWrapperInit libWrapper-api.js:803
    initialize#0 libWrapper-wrapper.js:187
    <anonymous> foundry.js:79693
    async* foundry.js:79675
foundry.js:747:30
    onError foundry.js:747
    call_wrapped libWrapper-wrapper.js:507
    <anonyme> listeners.js:135
    onError#0 libWrapper-wrapper.js:187
    _loadTranslationFile foundry.js:6774
    _getTranslations foundry.js:6705
    _getTranslations foundry.js:6704
    setLanguage foundry.js:6635
    initialize foundry.js:6601
    initialize foundry.js:7816
    call_wrapped libWrapper-wrapper.js:507
    libWrapperInit libWrapper-api.js:803
    initialize#0 libWrapper-wrapper.js:187
    <anonyme> foundry.js:79693
    <anonyme> foundry.js:79675

```

**Comment by esheyw** [comment]
[insert france joke here]

**Comment by p4535992** [comment]
try out v0.8.44

**Comment by Angor-de-Redjak** [comment]
Seems resolved.
Thank you!
