### ISSUE TITLE
[BUG] Module causes all buttons in Game Settings to get pushed out

### ISSUE THREAD

**Issue by GambetTV** [p4535992/foundryvtt-chat-portrait#33]
There is a minor formatting issue in "Configure Settings" caused by this module, which pushes all of the buttons and settings bars to get pushed 30-40 pixels to the right, which makes it look bad.

The issue comes from en.json, on this line:   "chat-portrait.settings.displayUnknown.choice.onlyNpc": "Affect any messages done from a NPC (need a compatible system with the 'npc' type like D&D5).",

This message, because it's in a dropdown menu, is too long. Either it needs to formatted to work with line breaks, or, I'd change the message to the following: "Affect NPC messages (need compatible system with the 'npc' type like D&D5)."

**Comment by p4535992** [comment]
i'll probably remove that oild feature because anonymus do a much better job now

**Comment by p4535992** [comment]
Solved
