### ISSUE TITLE
[BUG] Module puts many warnings about hovering into the console

### ISSUE THREAD

**Issue by OberstK** [p4535992/foundryvtt-chat-portrait#35]
**Module Version:** v0.9.1

**Before open any issue**

1) Enable the module setting _"Enable debugging"_
2) Click F12 go to the _console_ tab 
3) make the test you want and replicate the error
4) Go to the tab console open on point 2) and just right click and click 'Save as' and 'Save' or send a screenshot of the exception on the console.
5) Attach the text file on the github issue with all the logs related tot he module, or send a screenshot of the messages on the console.

**Describe the bug**
whenever the mouse hits any chat portrait the following warning is going into console:

module.js:30 chat-portrait | Can't hover in the chat portrait of the token '[object Object]'

**To Reproduce**
1. Go to chat
2. Hover over any chat message with portrait
3. See error

**Expected behavior**
No warnings on hover should come up

**Browser:**
 - Chrome

**Foundry Version:** 
11.309

**Game System:** 

**Logs**
[localhost-1695651904055.log](https://github.com/p4535992/foundryvtt-chat-portrait/files/12716292/localhost-1695651904055.log)

**Comment by p4535992** [comment]
Solved
