### ISSUE TITLE
[BUG] Generic CSS restricts <div> elements to half width.

### ISSUE THREAD

**Issue by mrkwnzl** [p4535992/foundryvtt-chat-portrait#36]
**Module Version:** v0.9.1

**Describe the bug**
`.chat-portrait-text-size-name-generic` includes `display: flex;` and defaults to `flex-direction: row;` (or is otherwise unset), I believe. This results in the behavior that `<div>` tags are only half the width of the chat card. Using `flex-direction: column;` will result in full width `<div>`, which would be default `<div>` behavior without Chat Portrait.

Since `.chat-portrait-text-size-name-generic` is added to `<span class="flavor-text">`, it’s putting the above rules for the container of the flavor text I have control over and it’s not as easy to for me to actually use the full width, since I can only put stuff in that container (or would otherwise need to add my own class to `<span class="flavor-text">`). On the other hand, if I really want some `<div>` elements with `flex-direction: row`, I can set that in my own container within `<span class="flavor-text">` pretty easily (which I’d probably already have, since default Foundry has full-width for `<div>`).

**To Reproduce**
1. Install the Cypher System.
2. Create a new World.
3. Open the newly created World.
4. Create a PC actor.
5. Open the PC actor sheet.
6. Click on one of the roll buttons.
7. The chat card is only half width for flavor text.

**Expected behavior**
I expect `<div>` elements to occupy the full width of the chat card by default.

**Screenshots**
This is how it looks now:

<img width="295" alt="Screenshot 2023-10-02 at 13 50 16" src="https://github.com/p4535992/foundryvtt-chat-portrait/assets/40534855/0530d096-d7d0-40df-ac4b-4f41eff70213">

This is how it’s supposed to look. This has `flex-direction: column;` added to `.chat-portrait-text-size-name-generic`:

<img width="295" alt="Screenshot 2023-10-02 at 13 51 04" src="https://github.com/p4535992/foundryvtt-chat-portrait/assets/40534855/fc0d2388-8fd2-4b17-8d00-c53a67d6767e">

For some extra context: There’s a way in the Cypher System to have the exact same output, but not as the flavor of a roll, which looks like this with Chat Portrait enabled (and no changes made):

<img width="295" alt="Screenshot 2023-10-02 at 13 53 14" src="https://github.com/p4535992/foundryvtt-chat-portrait/assets/40534855/11878cb3-68b3-458b-95b3-6bf8911ef4f0">

**Browser:**
 - Foundry Electron App.

**Foundry Version:** 
- 11.311

**Game System:** 
- Cypher System, but it’s using the generic CSS.

**Additional context**
I don’t think that a full Cypher System style is needed or worth it for this one change.

Thanks!

**Comment by mrkwnzl** [comment]
🤦‍♂️ Nevermind!

A simple `width: 100%` on my end works just as well. I tried that before, but it didn’t work. Probably a silly typo or something. Sorry about that.

**Comment by mrkwnzl** [comment]
I think the generic one is working well, actually. There's nothing too fancy in the Cypher System that would warrant that, now that I found that a simple `width: 100%` at the right place does the job.

**Comment by p4535992** [comment]
kk
