### ISSUE TITLE
[FEATURE] ChatPortraitEnabled Hook call to provide arguments

### ISSUE THREAD

**Issue by RossGosling** [p4535992/foundryvtt-chat-portrait#38]
When the 'ChatPortraitEnabled' Hook is invoked it doesn't provide any arguments, there's no way of determining whether you want to enable or disable the portrait without external context

Adding chatMessage, html, and speaker in as arguments you would be able to make informed decisions to prevent portrait display

[/src/scripts/ChatPortrait.js Line 36](https://github.com/p4535992/foundryvtt-chat-portrait/blob/d95dcc7e351f1a98cee7fc0ecba679d1952efe8f/src/scripts/ChatPortrait.js#L36)

**Comment by p4535992** [comment]
done on 0.9.4
