### ISSUE TITLE
Image Replacer not Working [BUG]

### ISSUE THREAD

**Issue by MisterQue77** [p4535992/foundryvtt-chat-portrait#41]
[localhost-1706639771026.log](https://github.com/p4535992/foundryvtt-chat-portrait/files/14102798/localhost-1706639771026.log)
**Module Version:** v0.0.0

**Before open any issue**

1) Enable the module setting _"Enable debugging"_
2) Click F12 go to the _console_ tab 
3) make the test you want and replicate the error
4) Go to the tab console open on point 2) and just right click and click 'Save as' and 'Save' or send a screenshot of the exception on the console.
5) Attach the text file on the github issue with all the logs related tot he module, or send a screenshot of the messages on the console.

**Describe the bug**
Dispite turning on the Image Replacer feature, nothing is appearing when checks or damage is dealt. I tried it on my normally server, and then tried it again on a completely blank server. I reinstalled and had no modules active other then it.
**To Reproduce**
Steps to reproduce the behaviour:
1. Turn on Chat Portrait
2. Turn on Image Replacer
3. Attempt anything that would normally produce the image.

**Expected behavior**
As far as I can tell, its a detailed as stated before
**Screenshots**
![Untitled-2](https://github.com/p4535992/foundryvtt-chat-portrait/assets/157548486/ab160e9b-293e-4288-8fd3-2f55a474915d)
**Browser:**
 -Chrome

**Foundry Version:** 
V11 Build 315
**Game System:** 
D&D5e 2.4.1
**Additional context**
Add any other context (like other modules installed) about the problem here.

**Comment by p4535992** [comment]
Should be fixed on 0.9.5 
P.S. i not sure if the feature still work

**Comment by MisterQue77** [comment]
That's intresting 🙂 well, if the feature is till active, I can't wait for the version to arrive
________________________________
