### ISSUE TITLE
[BUG] Not Working with Unknown Armies System

### ISSUE THREAD

**Issue by patrickburk1988** [p4535992/foundryvtt-chat-portrait#42]
Hello! I'm the developer of the Unknown Armies system, installable via the following URL: https://raw.githubusercontent.com/patrickburk1988/unknownarmies/main/system.json. Chat Portrait doesn't appear to be working fully with the system. Specifically, the image always renders as the default "mystery man" portrait. This happens regardless of whether the `Use Token Image` settings is enabled. There are no errors thrown in the console.

This may be something I can fix in the system itself, but I'm unsure of what steps need to be taken. Any insight would be appreciated!

**Comment by p4535992** [comment]
I can problably fix this on my side, but it's always advisable for the system to manage this on is own.

**Comment by patrickburk1988** [comment]
I'm down to fix it on my end, but I'm not quite sure how. Actor and token images appear to display and function normally in the system itself; it's only with this module that they don't show up. The only place I really mess with the images at all in my own code is in the sheet Handlebars:
```handlebars
<div class="portrait">
    <img data-edit="img" alt="{{actor.name}} portrait" src="{{actor.img}}">
    <button data-action="show-image"><i class="fas fa-image"></i></button>
</div>
```
Is there something different I need to be doing with how the actor image is assigned?

**Comment by p4535992** [comment]
Add on version 0.9.6 a module setting to disable my portrait in favor of the one on the system

**Comment by patrickburk1988** [comment]
Still doesn't work, sadly. I may have explained the problem poorly, as well. It's not that I've implemented my own custom portrait in the chat messages; it's that the chat message portrait provided by this module doesn't seem to detect any of the system's portrait/token images, despite them being stored in `actor.img` and `actor.token.texture`.

Here's one of the actors in the console, showing that the portrait and token images have both been assigned: 
![image](https://github.com/p4535992/foundryvtt-chat-portrait/assets/13472864/bb13c5ba-39b2-4927-ad7d-a693a2ee5b71)

Yet when I create a chat message for the actor, this is what it looks like:
![image](https://github.com/p4535992/foundryvtt-chat-portrait/assets/13472864/70756967-fc14-49fe-8fb7-e521deedbbf9)

**Comment by patrickburk1988** [comment]
I think I've figured it out, actually! I wasn't passing a `speaker` value when outputting a roll to the chat. I knew it was something goofy I was doing.

Thanks for looking into this!
