### ISSUE TITLE
for new dnd5e 3.x.x system - turn image off

### ISSUE THREAD

**Issue by Wade0004** [p4535992/foundryvtt-chat-portrait#43]
I love the functionality of having the chat colors configured to user config colors.  With the new DND 5e gamesystem, I'm getting double portraits.   can you make a box to turn off the "portrait" part of "chat portrait" ?
![image](https://github.com/p4535992/foundryvtt-chat-portrait/assets/74107522/f377bba2-b05a-44b7-b692-9fd283cd3a45)

**Comment by Wade0004** [comment]
I actually checked that one out, and maybe I'll ask them if they can change features to get what it is that I'm looking for.

Because, as the module is currently written it doesn't change colors based on user, but only based off of what it is that you are doing...  Like, you can chat "above the table" in one color, or "in character" in another color, and rolls are another color.  But as far as I could see, you can't say: "Squee is Blue", "Chieuw is Green", "GM is Red", "Reiger is Orange" like I am able to do with your module.   does that make sense?

**Comment by DivertedCircle** [comment]
I actually prefer the look of the portrait from this module over the new default. Any chance of an update to hide the default portrait, or override it with the module version?

**Comment by p4535992** [comment]
@Wade0004  add the module settings on 0.9.6
@DivertedCircle I thank you , but for a best compatibility between modules my advice is to disable my portrait in favor of the system one if present (like dnd5e, pf2e , ecc.)
