### ISSUE TITLE
[BUG] Module removes spaces from text with text formatting tags

### ISSUE THREAD

**Issue by pafvel** [p4535992/foundryvtt-chat-portrait#44]
**Module Version:** v0.9.6

**Describe the bug**
The css classes for displaying text that have `display: flex` will cause text with formatting tags to eliminate the space before and after the formatting tags. This is a problem for example when a system uses formatting in the flavor text for dice rolls. see this example from Dragonbane:
![chatportrait-db](https://github.com/p4535992/foundryvtt-chat-portrait/assets/91607056/13da9773-4cbb-4058-bda2-06b6b501c7e1)

I verified that it behaves the same way in DnD5e by injecting formatted text manually:
![chatportrait](https://github.com/p4535992/foundryvtt-chat-portrait/assets/91607056/88b6f7c5-345f-48c6-a41b-d670c88a9568)

**Expected behavior**
I verified that removing `display: flex` fixes the issue.
![chatportrait-db2](https://github.com/p4535992/foundryvtt-chat-portrait/assets/91607056/867b539f-0996-44e4-ba03-ed5f92cd3d47)

**Browser:**
Chrome v 123.0.6312.86

**Foundry Version:** 
11.315

**Game System:** 
DnD 5e
Dragonbane

**Comment by p4535992** [comment]
Apply your suggestion on 0.9.7

**Comment by pafvel** [comment]
Fix for Dragonbane confirmed. Thank you!
