### ISSUE TITLE
[BUG] Styling is only applied if not using the portrait image (1.0.0) 

### ISSUE THREAD

**Issue by nyvinter** [p4535992/foundryvtt-chat-portrait#49]
**Module Version:** v1.0.0

With the new version, the chat portrait and messages don't applies the styling choices such as circle, border colour, or background colour. If you turn of the custom stylings for message X, then it applies the colours. So something breaks when the chat portraits is used.

![image](https://github.com/p4535992/foundryvtt-chat-portrait/assets/117765791/433d3368-10c0-47c2-9581-5a8d43f5b104)
![image](https://github.com/p4535992/foundryvtt-chat-portrait/assets/117765791/6bf3533e-2d39-4b6d-a1b4-62d31480733b)

Per the settings, the roll message should have a circle portrait and blue background and border like player2.

**Comment by p4535992** [comment]
Fixed on 1.0.1
