### ISSUE TITLE
[BUG] Triple message headers

### ISSUE THREAD

**Issue by MarlQ** [p4535992/foundryvtt-chat-portrait#5]
**Module Version:** v0.8.8

Since the newest patch, the module triplicates the message headers.
This is a major issue in my system, due to styling, and makes the module unusable. 

![image](https://user-images.githubusercontent.com/15791893/195075850-62208223-51fa-4657-9b77-0bed5d5dd981.png)
![image](https://user-images.githubusercontent.com/15791893/195076011-7018fe42-c18a-454c-9c53-22a157be77de.png)

I checked the html in Foundry's dnd 5e system, and the same thing happens there;
just it's less noticeable visually with the default styling.

**Foundry Version:** 10.288

**Game System:** Any

**Comment by p4535992** [comment]
The triple header is like the new standard for make everyone happy in every system no much choice in that.
The problem is the style what module are you using for the black background ?

**Comment by Serban-AndreiC-2054619** [comment]
> The triple header is like the new standard for make everyone happy in every system no much choice in that. The problem is the style. What module are you using for the black background ?

Hi, sorry to butt in this issue, but it's bothering me a fair bit as well. Would it be much work to change it like it was before on my local copy, could you point me in the right direction? Or is the old way just not possible anymore?

**Comment by p4535992** [comment]
@Serban-AndreiC-2054619  @MarlQ  Like i said is a style issue...but i need some minimal information on the use case are you using the default style of foundry (i don't think so) ? are you using a third module fro the chat style (then name it) ? What system are you using ?

**Comment by p4535992** [comment]
To understand each other with the default foundry chat nobody is complaining, so it must be some other style applied to the chat .... I can also go blind if needed ... and go to style attempts but if I had the reference to the module for a comparison I would fix the style problem immediately

**Comment by p4535992** [comment]
Ty @Serban-AndreiC-2054619 sadly this is a problem on my side, if i fix that for you i make another person angry....

I separated at the "line" level the timestamp from the name (in dnd5e because in other systems it is different and this is another reason for the separation) for the case in which the name was long and was "truncated".

To make things right I should do a chat portrait dedicated to dnd5e.

Mayber you better off with https://github.com/nickelpro/simply-portraits ?

**Comment by Serban-AndreiC-2054619** [comment]
Thanks for the quick reply. Simply Portraits is nice, but I still prefer your mod since the options to outline cards in the player's color makes for a more cohesive experience. I'm just gonna try to get used to the new look : )

**Comment by p4535992** [comment]
i'll try some css tweak for make a little more compact .

**Comment by p4535992** [comment]
@MarlQ i tried to fix your issue too. Let me know if the issue is persistent .  Let me know the  module are you using for the black background for confirm the resolution.

**Comment by MarlQ** [comment]
The issue still persists; though now the messages have two headers instead of three. The "module" is in fact my own system, but the css can not be fixed, due to the header duplication. That will break any system that styles the header with padding, margin, different background (especially gradients), and borders. Of course I *could* fix it by a change in the message html, but that would still break all old messages, etc. I'm not exactly sure _why_ you did it like this, but I suggest you could make it optional as a setting.

I will use Simply Portraits for now though, as it seems sufficient.

**Comment by p4535992** [comment]
Should be solved for everyone even for the @MarlQ use case
