### ISSUE TITLE
[BUG]Issue with Monk's Little Details round markers styling

### ISSUE THREAD

**Issue by dstein766** [p4535992/foundryvtt-chat-portrait#8]
Sorry - I'm not sure whether I should be entering issues here or on the original module author's site.  (You did address an issue I put on the other site, so you're clearly paying attention, but not sure what you prefer.)  Anyway, I entered this issue a few days ago.

https://github.com/ShoyuVanilla/FoundryVTT-Chat-Portrait/issues/121

**Comment by p4535992** [comment]
should be fixed with 0.8.26
